import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import cookie from "js-cookie";
import { useRouter } from "next/router";
import Navbar from "../components/navbar.js";
import LogForm from "../components/logForm.js";

import {
  MailOutlined,
  AppstoreOutlined,
  SettingOutlined,
} from "@ant-design/icons";
export default function Home() {
  cookie.set("myCookieName", "some-value2122", { expires: 1 / 24 });

  function changeBackgroundColor(e) {
    e.target.style.background = "green";
  }

  function handleMouseOut(e) {
    e.target.style.background = "";
  }

  const router = useRouter();
  const [token, setToken] = useState(false);
  const goProducts = () => {
    router.push("/home");
  };
  const [current, setCurrent] = useState("mail");

  return (
    <>
      <div className={styles.container}>
        <div className="header">
          {" "}
          <Navbar />
        </div>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            <LogForm />
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
