import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import Navbar from "../../components/navbar.js";
import Cookies from "js-cookie";
import { Nav, Container } from "react-bootstrap";
export default function Home() {
  const router = useRouter();
  const [cookie, setCookie] = useState(Cookies.get("myCookieName"));
  const goProducts = () => {
    router.push("/");
  };

  const deleteCookie = () => {
    Cookies.remove("myCookieName");
    setCookie(null);
  };

  return (
    <div className={styles.container}>
      <div className="header">
        {" "}
        <Navbar />
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => goProducts()}>Home</button>
        <button onClick={() => deleteCookie()}>delete cookie</button>
        {cookie !== null ? (
          <h1>se obtuvo la cookie, de valor: {cookie} </h1>
        ) : (
          <h1>There is no cookie</h1>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" s"}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
